site_name: Raspberry Pi
site_author: dvjlabs team
copyright: >
  dvjlabs (c) 2022-inf<br>
  <a href="#__consent">Change Cookie Settings</a>

# ----------------------------------------------------------------------

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: it
  features:
    - navigation.tabs
    - navigation.footer
    - toc.integrate
    - content.code.copy
  font: false
extra:
  consent:
    title: Consenso all'utilizzo dei cookies
    description: >
      Questo sito memorizza alcuni cookies solo per riconoscere un visitatore
      che non è alla sua prima visita e alcune preferenze, come il tema di visualizzazione
      della pagina selezionato.<br>
      Se non acconsenti, questa finestra riapparirà ogni volta che riapri il sito.<br>
      Se vuoi cambiare le tue scelte, in fondo alla pagina trovi un link per modificarle ;)
    actions:
      - accept
      - reject

extra_css:
  - stylesheets/extra.css

# ------------------------------------------------

markdown_extensions:
  - admonition: {}
  - attr_list: {}
  - toc: {}
  - def_list: {}
  - pymdownx.emoji: {}
  - pymdownx.tasklist: { custom_checkbox: True }
  - pymdownx.highlight: { anchor_linenums: True }
  - pymdownx.inlinehilite: {}
  - pymdownx.snippets: {}
  - pymdownx.superfences: {}

# ------------------------------------------------

nav:
  - Home: index.md
  - Raspberry Pi:
      - Introduzione: rpi/00_intro.md
      - Installazione: rpi/01_installation.md
      - Base: rpi/02_base.md
      - Remoto: rpi/03_remote.md
      - Multimedia: rpi/04_multimedia.md
  - IoT:
      - RPi e sensori: iot/00_intro.md
      - WiringPi: iot/01_wiringpi.md
      - GPIO: iot/02_gpio.md
      - breadBoard: iot/03_breadboard.md
  - OpenCV:
      - Introduzione: opencv/00_intro.md
      - OpenCV: opencv/01_OpenCV.md
